# Generated by Django 2.0.8 on 2018-08-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='_note_children_+', to='notes.Note', verbose_name='Child notes'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='notes.Tag', verbose_name='Tags'),
        ),
    ]
