# Generated by Django 2.0.8 on 2018-08-11 09:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], verbose_name='Tags'),
        ),
    ]
