# Generated by Django 2.0.8 on 2018-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='note',
            name='syntax',
            field=models.CharField(blank=True, choices=[('CU', 'custom'), ('SI', 'simple')], default='SI', max_length=2, null=True),
        ),
    ]
