# Generated by Django 2.0.8 on 2018-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180811_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_expanded',
            field=models.BooleanField(default=False, verbose_name='Expanded'),
        ),
    ]
